# Generated by Django 2.2 on 2020-08-19 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPersona', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('numLibros', models.IntegerField()),
                ('adeoudo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMaterial', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('titulo', models.CharField(max_length=40)),
                ('anio', models.IntegerField()),
                ('status', models.CharField(max_length=40)),
                ('Biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca3.Biblioteca')),
            ],
        ),
    ]
