# Generated by Django 2.2 on 2020-08-19 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('codigo', models.CharField(max_length=40)),
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('fechaSalida', models.CharField(max_length=40)),
                ('fechaRegreso', models.CharField(max_length=40)),
                ('persona', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='biblioteca3.Persona')),
            ],
        ),
    ]
