# Generated by Django 2.2 on 2020-08-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca3', '0003_alumno_libro_profesor_revista'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fotoPortada',
            field=models.ImageField(blank=True, default='fotos_tapa/default.png', upload_to='fotos_tapa/'),
        ),
    ]
